# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_be_rented', models.BooleanField(default=True)),
                ('book_name', models.CharField(max_length=256)),
                ('rent_cost', models.FloatField()),
                ('rent_estimate_time', models.DateTimeField()),
                ('author', models.ManyToManyField(to='book_author.BookAuthor')),
            ],
        ),
    ]
