# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_rentuser_books'),
        ('book', '0003_auto_20170618_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.RentUser'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rent_estimate_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 18, 19, 45, 12, 406889)),
        ),
    ]
